from PyQt5.QtWidgets import (QApplication, QWidget, QListWidget, QPushButton,
QTextEdit, QLineEdit, QLabel, QVBoxLayout, QHBoxLayout)

app = QApplication([])
notes_win = QWidget()
notes_win.setWindowTitle('smart notes')
notes_win.resize(900,600)
list_notes = QListWidget()
list_notes_label = QLabel('Список заметок')

but_not_create = QPushButton('Создать заметку')
but_not_del = QPushButton('Удалить заметку')
but_not_save = QPushButton('Сохранить заметку')

list_tags = QListWidget()
list_tags_label = QLabel('Список тегов')

but_tag_dd = QPushButton('Добавить тег')
but_tag_de  = QPushButton('Удалить тег')
but_tag_sher = QPushButton('Поиск по тегу')

field_txt = QTextEdit()
field_tag = QLineEdit()
field_tag.setPlaceholderText('Введите тег...')

layout_notes = QHBoxLayout()
col_1 = QVBoxLayout()
col_2 = QVBoxLayout()
row_1 = QHBoxLayout()
row_2 = QHBoxLayout()
row_3 = QHBoxLayout()
row_4 = QHBoxLayout()
col_1.addWidget(field_txt)
col_2.addWidget(list_notes_label)
col_2.addWidget(list_notes)
row_1.addWidget(but_not_create)
row_1.addWidget(but_not_del)
row_2.addWidget(but_not_save)
col_2.addLayout(row_1)
col_2.addLayout(row_2)
col_2.addWidget(list_tags_label)
col_2.addWidget(list_tags)
col_2.addWidget(field_tag)
row_3.addWidget(but_tag_dd)
row_3.addWidget(but_tag_de)
row_4.addWidget(but_tag_sher)

col_2.addLayout(row_3)
col_2.addLayout(row_4)

layout_notes.addLayout(col_1, stretch = 2)
layout_notes.addLayout(col_2, stretch = 1)
notes_win.setLayout(layout_notes)
notes_win.show()
app.exec_()